# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: docker build
      run: |
        docker pull devkitpro/devkitarm
        docker run -e ENABLE_COMPATIBILITY_REPORTING -v $GITHUB_WORKSPACE:/build_dir devkitpro/devkitarm /bin/bash -ex /build_dir/.travis/build.sh
    
    - name: before-tag
      run: 
        CUSTOM_TAG= git --git-dir $GITHUB_WORKSPACE/Luma3DS/.git rev-parse --short --verify HEAD
    
    - name: tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.key }}
        
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: $GITHUB_WORKSPACE/Luma3DS/boot.firm
      env:
        GITHUB_TOKEN: ${{ secrets.key }}
      
